#---------------------------async_lib_service-----------------------
lib_api:
    build: .
    env_file:
        - lib.env
    command: gunicorn wsgi:app -k aiohttp.worker.GunicornWebWorker -b 0.0.0.0:8080
    ports:
        - "7070:8080"